### ISSUE TITLE
wildcards in step definitions?

### ISSUE THREAD

**Issue by mikelietz** [spyoungtech/behave-webdriver#72]
I don't think this is a bug as much as lack of coding experience. I'm porting over some very rudimentary lettuce_webdriver features and steps, and I'm struggling for a clean replacement for "I should see..."

One such feature line for this is:

    Scenario: Testing Webdriver
      When I open the url "http://my.login.page"
      Then I should see "Forgot Your Password?"

Of the three definitions below, only the first one works. The latter two are not recognized and behave suggests a snippet like the first one.

    @then(u'I should see "Forgot Your Password?"')
    def step_impl(context):
      assert context.behave_driver.element_contains('body', 'Forgot Your Password?')

    @then(u'I should see "([^"]*)?"')
    def step_impl(context, value):
      assert context.behave_driver.element_contains('body', value)

    @then(u'I should see "([^"]*)?"')
    def step_impl(context, value):
      context.execute_steps( u"""
        then I expect that element "body" contains the text "{text}')
      """).format(text = value)

**Comment by spyoungtech** [comment]
By default, the 'parse' matcher is in use.  
Defining a generic step for this use should be as simple as the following:

```python
@then(u'I should see "{text}"')
def expect_some_text(context, text):
    assert context.behave_driver.element_contains('body', text)
```

The problem you're encountering with the latter two steps is that, in order to use regex matching, you'd need to change the step matcher first.

So you could define the same kind of step using the regex matcher this way

```python
from behave import use_step_matcher
use_step_matcher('re')

@then(u'I should see "([^"]*)?"')
def step_impl(context, value):
  assert context.behave_driver.element_contains('body', value)

```

If you change the matcher, don't forget to change it back as needed, so your other steps don't unexpectedly stop working. 

For more info, you can read about this more in the [behave documentation](https://behave.readthedocs.io/en/latest/tutorial.html?highlight=step_matcher#step-parameters)

**Comment by mikelietz** [comment]
Thank you! I wasn't sure if this was better asked there or here.
